repos:
  - repo: local
    hooks:
      - id: ruff
        name: ruff
        entry: uv run ruff check --fix --exit-non-zero-on-fix
        language: system
        types_or: [ python, pyi ]
        require_serial: true
        files: \.py$
      - id: ruff-format
        name: ruff-format
        entry: uv run ruff format
        language: system
        types_or: [ python, pyi ]
        require_serial: true
        files: \.py$